spring.main.banner-mode=off
logging.level.org.springframework=ERROR

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=embedded
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://139.9.221.243:5432/skychat
spring.datasource.username=skychat
spring.datasource.password=5ZNfEAXYABW5

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true