spring.profiles.active=local
logging.level.org.springframework=ERROR

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.use-new-id-generator-mappings=false

spring.socket.channel=WEBSOCKET

#spring.sql.init.mode=never
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=
#spring.jpa.show-sql: true